server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://sdadgz.cn:3307/website
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
  mvc:
    static-path-pattern: ${my.file-config.staticPath}** # 静态资源访问
  resources:
    static-locations: file:${my.file-config.uploadPath}

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.sdadgz.web_springboot.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: cn.sdadgz.web_springboot.entity

my:
  server: # 上传到服务器需要改这个
    name: http://localhost
    uploadPath: 'D:/下载/不用思考，删这个文件夹/' # 文件下载到哪里，记得屁股加个杠


  file-config:
    uploadPath: '${my.server.uploadPath}'
    staticPath: '/static/'
    downloadPath: '${my.server.name}:${server.port}${my.file-config.staticPath}' # 存url到数据库时用的他
