server:
  port: 8000
#  ssl:
#    key-store: classpath:sdadgz.cn.jks
#    key-store-type: JKS
  servlet:
    encoding:
      force: true # 静态资源乱码
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://sdadgz.cn:3307/website?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      max-active: 200
#      min-idle: 6
#    tomcat:
#      max-active: 200
  redis:
    port: 6379
    host: sdadgz.cn
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
  mvc:
    static-path-pattern: ${my.file-config.staticPath}** # 静态资源访问
  resources:
    static-locations: file:${my.file-config.uploadPath}
# mybatis原生，删了试试会不会报错
#mybatis:
#  mapper-locations: mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#  type-aliases-package: cn.sdadgz.web_springboot.entity

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  type-aliases-package: cn.sdadgz.web_springboot.entity

my:
  server: # 上传到服务器需要改这个
    name: https://sdadgz.cn
    uploadPath: '/usr/local/springboot/static/' # 文件下载到哪里，记得屁股加个杠
    localhostIp: '85.230.0.1'

  file-config:
    uploadPath: '${my.server.uploadPath}'
    staticPath: '/static/' # 访问前缀，不是物理地址
    downloadPath: '${my.file-config.staticPath}' # 存url到数据库时用的他

  unification-config:
    response-lists: 'lists'
    response-total: 'total'

# 日志
logging:
  level:
    root: info
  file:
    name: test.log
    max-size: 10MB
    clean-history-on-start: true